### PR TITLE
Trap forces

### PR DESCRIPTION
**Pull request by Zaretsky-Daniel**
Added trap forces as an option for regular traps. Each trap can have its own depth/size. Calculating the force upon each particle is done with the matrix of traps.

Also fixed some minor bugs, and added some comments.

### CODE REVIEW

**Review by giladpollack — APPROVED** [review]
Looks good, I approve

**Comment by giladpollack** [comment]
Just one thing - You called the function getSingleTrapForce, when in fact it gets all the traps for a single particle. So I think you should change it to be called getTrapForcesForSingleParticle or something like that

**Comment by giladpollack** [comment]
Also, this closes issue #3

**Comment by Zaretsky-Daniel** [comment]
True, I wanted to change that, but forgot. Will do.

**Pull request merged**
